### ISSUE TITLE
Can't run the script

### ISSUE THREAD

**Issue by fell-lucas** [wodim/wow-discord-rich-presence#1]
Hey, just wanted to try your code out, I ran the script some times without debug mode and it got stuck, so I reran it with debug and it showed me this error:

![Capture](https://user-images.githubusercontent.com/47724710/79055459-af999900-7c23-11ea-8cea-0825572875a1.PNG)

WoW version: 3.3.5a
Addon is installed
Game is running in windowed mode

![WoWScrnShot_041120_184048](https://user-images.githubusercontent.com/47724710/79055519-2040b580-7c24-11ea-807b-6547af463bc0.jpg)

**Comment by wodim** [comment]
I've just pushed a fix so you can properly follow the guide (and set the correct MY_WIDTH value for your resolution)
